Azure/device-simulation-dotnet

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
SimulationAgent/DependencyResolution.cs
device-simulation.sln

- [x ] All new and existing tests passed.
Remove duplicate code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/74)

Remove duplicate code from IFactory implementation

---

WebService/Auth/AuthMiddleware.cs

Fix for https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/issues/29
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/98)

Retry downloading OpenId certs in case of failure

---

Services/DeviceMethods.cs
Services/data/devicemodels/scripts/FirmwareUpdate-method.js
Services/data/devicemodels/scripts/reboot-method.js

…ion handler to callback function called by hub.
- [ x] Bug fix
Set method result for firmwareupdate and reboot to empty string @ execution completion.  Add exception handler to function pointer that the hub calls for method execution.
...
**Checklist:**
- [x ] All tests passed
- [ x] The code follows the code style and conventions of this project

Set method result to empty string @ execution completion.  

---

Services.Test/Concurrency/PerSecondCounterTest.cs
Services.Test/Concurrency/RatedCounterTest.cs
Services/Concurrency/RatedCounter.cs
Services/DeviceMethods.cs

1. fix null ref exception, see #122 
2. backport mitigation for flaky test
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/128)

Fix null ref exception

---

.travis.yml
Services.Test/Services.Test.csproj
Services/Services.csproj
SimulationAgent.Test/SimulationAgent.Test.csproj
SimulationAgent/SimulationAgent.csproj
WebService.Test/WebService.Test.csproj
WebService/WebService.csproj
scripts/.functions.sh
scripts/build.cmd
scripts/compile.cmd
scripts/docker/build.cmd
scripts/run.cmd

Upgrade libraries and move to .NET Core 2.0
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/130)

Upgrade to .NET Core 2.0 and upgrade dependencies

---

scripts/docker/Dockerfile

Fix the Docker image, to use .NET Core 2.0.3
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/131)

Change Docker base image to use .NET Core 2.0.3

---

scripts/docker/Dockerfile

Use Docker base image with .NET Core 2.0.3
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/132)

Upgrade Docker image to 2.0.3 [November branch]

---

.travis.yml
Services/DeviceModels.cs
Services/DeviceModelsGeneration.cs
Services/Models/DeviceModel.cs
Services/Models/Simulation.cs
Services/Simulation/InternalInterpreter.cs
Services/Simulation/ScriptInterpreter.cs
SimulationAgent/DeviceState/DeviceStateActor.cs
SimulationAgent/SimulationRunner.cs
WebService/Runtime/Config.cs
WebService/v1/Models/DeviceModelApiModel/DeviceModelSimulation.cs
WebService/v1/Models/SimulationApiModel/DeviceModelApiModelOverride.cs
WebService/v1/Models/SimulationApiModel/DeviceModelSimulationOverride.cs
WebService/v1/Models/SimulationApiModel/DeviceModelSimulationScriptOverride.cs
WebService/v1/Models/SimulationApiModel/DeviceModelTelemetryMessageSchemaOverride.cs
WebService/v1/Models/SimulationApiModel/DeviceModelTelemetryOverride.cs

New logic for customizing sensors and selected pre-configured behavior like increasing, decreasing and random numbers.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/146)

Internal scripts for increasing/decreasing/random

---

WebService/appsettings.ini
device-simulation.sln
docs/ENVIRONMENT_VARIABLES.md

Use an optional env var to define the log level
**Checklist:**

Use env var to define log level

---

Services.Test/SimulationsTest.cs
Services/DeviceModels.cs
Services/Devices.cs
Services/Simulations.cs
SimulationAgent/SimulationRunner.cs
WebService/appsettings.ini

Use batch operations to create the simulated devices.
Delete devices when a simulation is deleted (not when it's stopped/completed).
**Checklist:**

Create devices using batch operations

---

Services.Test/SimulationsTest.cs
Services/Models/Simulation.cs

- Ignore null value for `InitialState`, `Scripts`, `MessageTemplate`, `MessageSchema`
...
**Checklist:**

Fix for override stock device model with null value

---

Services.Test/DeviceModelsGenerationTest.cs
Services/DeviceModelsGeneration.cs

- Add null check for `MessageSchema`
...
**Checklist:**

Fix exceptions when override stock device model

---

WebService/Properties/launchSettings.json

Editing launchSettings.json to reference actual environment variables.  This will make the solution debuggable from Visual Studio without needing to edit the launchSettings.json file. This should reduce the risk of checking in launchSettings.json with real connection strings (and secrets) in it. 
**Checklist:**

Use env vars in launchSettings.json

---

Services/Devices.cs

- set sdkClient `SetRetryPolicy` to `NoRetry`
...
**Checklist:**

Disable sending telemetry retry

---

Services/data/devicemodels/chiller-01.json
Services/data/devicemodels/elevator-01.json
Services/data/devicemodels/truck-01.json

Use AMQP for the stock device models, in order to reduce the CPU utilization.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/189)

Change stock models to use AMQP

---

Services.Test/Services.Test.csproj
Services/Services.csproj
SimulationAgent.Test/SimulationAgent.Test.csproj
WebService.Test/WebService.Test.csproj

Upgrade Azure IoT SDK: Devices Client 1.5.2 to 1.7.0
Upgrade test dependencies
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/187)

Upgrade Azure IoT SDK: Devices 1.4.1 to 1.6.0

---

Services/data/devicemodels/engine-02.json
Services/data/devicemodels/scripts/EmptyTank-method.js
Services/data/devicemodels/scripts/elevator-01-state.js
Services/data/devicemodels/scripts/elevator-02-state.js
Services/data/devicemodels/scripts/engine-01-state.js
Services/data/devicemodels/scripts/engine-02-state.js
docs/DEVICE_MODELS.md

* ASA query can not process zero value in UDF function, we avoid to use
default zero value for engine device model
* TODO: Revert this commit once ASA fix the bug
...
**Checklist:**

Change fuellevel and vibration value to non-zero value

---

Services/data/devicemodels/engine-02.json
Services/data/devicemodels/scripts/EmptyTank-method.js
Services/data/devicemodels/scripts/elevator-01-state.js
Services/data/devicemodels/scripts/elevator-02-state.js
Services/data/devicemodels/scripts/engine-01-state.js
Services/data/devicemodels/scripts/engine-02-state.js
docs/DEVICE_MODELS.md

This reverts commit 2f8598654e7f4b51dcd6647ab00955e5b13acdfc.
...
**Checklist:**

Revert "Change fuellevel and vibration value to non-zero value (#206)"

---

.vscode/launch.json
README.md

Enabling use of VS Code for debugging. Improve experience/documentation.
**Checklist:**

Enabling use of VS Code for debugging

---

docs/CODEOWNERS

Updating owners list
...
**Checklist:**

Updating owners list

---

README.md

...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/233)

Added a "Deploy to Azure" button.

---

Services/Models/Protobuf/Truck.cs
Services/Models/Protobuf/proto/Truck.proto
Services/data/devicemodels/truck-01-protobuf.json

Fixing params in Truck-Protobuf model
Fixing namespace
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/238)

Protobuf bug fixes

---

WebService/v1/Controllers/SimulationsController.cs

Fix the bug introduced by not waiting on async method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/246)

await on async method

---

Services.Test/StockDeviceModelTest.cs
Services/Services.csproj
Services/data/devicemodels/delivery-truck-01.json
Services/data/devicemodels/delivery-truck-02.json
Services/data/devicemodels/scripts/delivery-truck-01-state.js
Services/data/devicemodels/scripts/delivery-truck-02-state.js

The Remote Monitoring solution needs two new device models for a demo scenario for Time Series Insights. 
The two new delivery trucks run a set route. One truck runs the normal route, and one takes an alternate route at a higher elevation, causing the cargo temperature to drop. The values can then be compared and inspected in Time Series Insights.
This change includes:
* Device models for delivery-truck-01 and delviery-truck-02
* State scripts for the trucks that run on a predefined set of values.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/249)

Add delivery truck device model that runs on a predefined loop

---

WebService.Test/v1/Controllers/DeviceModelScriptsControllerTest.cs
WebService/v1/Controllers/DeviceModelScriptsController.cs

* Update file type for uploaded Javascript file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/256)

Update file type

---

Services/Models/Simulation.cs
WebService/v1/Filters/ExceptionsFilterAttribute.cs
WebService/v1/Models/SimulationApiModel/SimulationApiModel.cs

Fix duplicate iothub connect strings in `Simulation` model.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/262)

Add dupl check for the iothub connect string

---

PartitioningAgent.Test/AgentTest.cs
PartitioningAgent/Agent.cs
Services.Test/SimulationsTest.cs
Services/Devices.cs
Services/Models/Simulation.cs
Services/Simulations.cs
WebService/v1/Models/SimulationApiModel/SimulationApiModel.cs

* Add devices bulk deletion support
* Add `ActiveNow` to simuation api model
**Todos:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/275)

Devices bulk deletion support

---

Services/Simulations.cs

Reset simulation deletion state for toggle(`enable`/`disable`) a simulation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/291)

Reset simulation deletion state for toggle(enable/disable) a simulation

---

SimulationAgent.Test/DeviceProperties/DevicePropertiesActorTest.cs
SimulationAgent/DeviceProperties/DevicePropertiesActor.cs

**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/312)

Code cleanup after the fix for property updates was merged.

---

Services.Test/Statistics/SimulationStatisticsTest.cs
Services/Devices.cs
Services/Models/Simulation.cs
Services/Simulations.cs
SimulationAgent.Test/DeviceState/DeviceStateActorTest.cs
SimulationAgent.Test/SimulationThreads/DeviceTelemetryTaskTest.cs
SimulationAgent/Agent.cs
WebService.Test/v1/Controllers/SimulationsControllerTest.cs
WebService/v1/Controllers/SimulationsController.cs
WebService/v1/Models/IoTHubApiModel.cs

1. Add a new endpoint, not exposed to UI, to kick off a job to delete all the devices in a hub
2. Increase the timeout for import jobs from 1 hour to 48 hours
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/310)

New (admin) endpoint to delete all devices

---

Services/data/templates/multiple-simulations-template.json

* Fixing default sim not starting issue
* changing order of default sims for UI
* Adding description
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/318)

Fixing default simulations not starting issue

---

Services.Test/DeviceModelScriptsTest.cs
Services.Test/ReplayFileServiceTest.cs
Services/DeviceModelScripts.cs
Services/Models/DataFile.cs
Services/Models/Simulation.cs
Services/ReplayFileService.cs
Services/Runtime/ServicesConfig.cs
Services/Services.csproj
Services/Simulation/JavascriptInterpreter.cs
WebService.Test/WebService.Test.csproj
WebService.Test/v1/Controllers/DeviceModelScriptsControllerTest.cs
WebService/Runtime/Config.cs
WebService/Startup.cs
WebService/WebService.csproj
WebService/appsettings.ini
WebService/v1/Controllers/DeviceModelScriptsController.cs
WebService/v1/Controllers/ReplayFileController.cs
WebService/v1/Models/DeviceModelScriptListModel.cs
WebService/v1/Models/ReplayFileApiModel.cs
docs/CODEOWNERS

APIs to upload, get, validate replay file.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/333)

Replay file  APIs

---

Services/StorageAdapter/StorageAdapterClient.cs

Fix for Status API failing in device Simulation. 
Cause of bug: DS status check was not updated after the Status APIs were changed in RM.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/340)

StorageAdapter Status check bug fix

---

.travis.yml
PartitioningAgent.Test/PartitioningAgent.Test.csproj
PartitioningAgent/PartitioningAgent.csproj
Services.Test/Services.Test.csproj
SimulationAgent.Test/SimulationAgent.Test.csproj
SimulationAgent/SimulationAgent.csproj
WebService.Test/WebService.Test.csproj
WebService/Startup.cs
WebService/WebService.csproj
scripts/docker/Dockerfile

Update to dotnet version 2.1
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/344)

Update dot net version

---

Services.Test/StockDeviceModelTest.cs
Services/Services.csproj
Services/data/devicemodels/delivery-truck-01.json
Services/data/devicemodels/delivery-truck-02.json
Services/data/devicemodels/scripts/delivery-truck-01-state.js
Services/data/devicemodels/scripts/delivery-truck-02-state.js
scripts/docker/build
scripts/docker/build.cmd
scripts/docker/content/run.sh
scripts/docker/content/set_env.sh

We are integrating key vault in RM. Hence, in RM deployments we would not have iotHubConnectionString and storageAdapterWebServiceUrl as environment variables. Hence, a script has been added to call keyvault and set the necessary variables before in the EntryPoint of Docker container. The script is benign, as in, if Keyvault name, AppId, and AppSecret are available through environment variables, only then the script would execute.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/346)

Keyvault integration into RM

---

Services/Services.csproj

Updated the IoT Hub SDKs to the following versions:
Devices: 1.18.1
Devices.Client: 1.20.3
**Checklist:**

Updating IoT Hub Client and Service SDK versions.

---

PartitioningAgent.Test/PartitioningAgent.Test.csproj
Services.Test/Services.Test.csproj
Services/Services.csproj
SimulationAgent.Test/SimulationAgent.Test.csproj
WebService.Test/WebService.Test.csproj
WebService/WebService.csproj

Dependency updates for monthly rollout cadence. 3 breaking changes in the form of major dependency version updates, 2 for Autofac and 1 for OpenIDConnect.
- [x ] Enhancement
- [x ] Breaking change (breaks backward compatibility)
**Checklist:**
- [x ] All tests passed
- [x ] The code follows the code style and conventions of this project
- [x ] I have updated the documentation accordingly

Updated dependency versions for monthly rollout cadence
