- Services/Concurrency/Timer.cs
- SimulationAgent/DependencyResolution.cs
- SimulationAgent/Simulation/DeviceActor.cs
- SimulationAgent/Simulation/DeviceStatusLogic/Status.cs
- SimulationAgent/Simulation/DeviceStatusLogic/UpdateDeviceState.cs
- SimulationAgent/Simulation/DeviceStatusLogic/UpdateReportedProperties.cs
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] The code follows the code style and conventions of this project.
Moved property structure polling to its own thread for scale/load reasons.
scale/load, code clarity
> Move desired property check to own thread

- SimulationAgent/Program.cs
A temporary workaround to allow the device twin deserialization regardless of some internal breaking change/regression.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/107)
> Temporary workaround to fix twin json deserialization

- Services.Test/helpers/TargetLogger.cs
- Services/DeviceModels.cs
- Services/Diagnostics/Logger.cs
- SimulationAgent/DeviceTelemetry/DeviceTelemetryActor.cs
- SimulationAgent/SimulationRunner.cs
- WebService/v1/Models/SimulationApiModel/DeviceModelSimulationOverride.cs
Apply the user customizations to the device models, e.g. custom telemetry frequency and custom device state simulation frequency.
Fix a regression affecting device models with multiple telemetry messages.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/141)
> Use custom frequency for telemetry and device state

- Services/DeviceModelsGeneration.cs
The service throws a nullref exception for the optional field for Initial State. This change updates the Generate() method to make the InitialState object nullable.
Log output:
```
[INFO][2017-12-04 20:15:42.979][WebService.9806116b-d147-4053-973f-200b5887439a][SimulationRunner:UpdateDevicesStateThread] Device state loop completed, {"durationMsecs":0}
[INFO][2017-12-04 20:15:43.331][WebService.9806116b-d147-4053-973f-200b5887439a][SimulationRunner:Stop] Stopping simulation...
[INFO][2017-12-04 20:15:48.085][WebService.9806116b-d147-4053-973f-200b5887439a][Simulations:UpsertAsync] Modifying simulation via PUT.
[INFO][2017-12-04 20:15:56.345][WebService.9806116b-d147-4053-973f-200b5887439a][SimulationRunner:Start] Starting simulation..., {"Id":"1"}
[INFO][2017-12-04 …
```
> Fix null reference exception in DeviceModelsGeneration

- Services.Test/IotHubConnectionStringManagerTest.cs
- Services/Simulations.cs
Service currently returns 400 Invalid Input for an ETag mismatch, so the UI doesn't show the correct error message:
See:
https://github.com/Azure/pcs-simulation-webui/issues/73 
Also added fix for the build warnings for Assert.ThrowsAsync in IotHubConnectionStringManagerTest.
**Checklist:**
> Return 409 Conflict instead of invalid input for ETag mismatch

- Services/Devices.cs
- Services/IotHub/IotHubConnectionStringManager.cs
- Services/PreprovisionedIotHub.cs
- Services/Runtime/DeploymentConfig.cs
- WebService/DependencyResolution.cs
- WebService/Runtime/Config.cs
- WebService/appsettings.ini
- WebService/v1/Controllers/StatusController.cs
- WebService/v1/Models/StatusApiModel.cs
- docs/API_SPECS_SERVICE.md
- docs/ENVIRONMENT_VARIABLES.md
Add new configuration settings storing information about the IoT Hub deployed.  If the information is available, the status endpoint now returns a new property, with a URL to open the hub metrics in the Azure portal.
**Checklist:**
> When available, return a URL to the metrics of the pre-provisioned hub

- Services/IotHub/IotHubConnectionStringManager.cs
- WebService/v1/Models/SimulationApiModel/SimulationIotHub.cs
When the user entered a custom connection string that was all whitespace, the backend would read it as null and set it to the default hub. If the solution didn't have a pre-provisioned hub, the service would run and silently fail. 
This change:
Adds additional validation for all-whitespace strings
Checks that the default hub can be connected to and has the proper permissions. 
**Checklist:**
> Throw error on all-whitespace connection string & validate default hub

- README.md
Fix for:
https://github.com/Azure/device-simulation-dotnet/issues/39
The relative links don't resolve to the wiki page ending up in a 404. This update changes the URL links to be the full relative link to the documentation page.
**Checklist:**
> Use absolute instead of relative links to wiki

- Services.Test/DevicesTest.cs
- Services/Devices.cs
- Services/IotHub/RegistryManagerShim.cs
Remove old code used to stop the simulation via cancellation token. The old code was interfering with the new state machine, where timeouts are actually errors.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/162)
> Remove old code used to detect simulation stop via cancellation token

- SimulationAgent.Test/DeviceState/DeviceStateActorTest.cs
- SimulationAgent.Test/SimulationAgent.Test.csproj
- SimulationAgent.Test/SimulationRunnerTest.cs
- SimulationAgent/DeviceState/DeviceStateActor.cs
- SimulationAgent/SimulationRunner.cs
- WebService.Test/v1/Controllers/StatusControllerTest.cs
- WebService/DependencyResolution.cs
- WebService/v1/Controllers/StatusController.cs
- Allow `DeviceStatusActor` report `IsDeviceActive` 
- `SimulationRunner` count `active` devices
- Add `ActiveDeviceCount` in `status` API
**Checklist:**
> Add active device count for status API

- Services/data/devicemodels/scripts/FirmwareUpdate-method.js
Related to https://github.com/Azure/device-simulation-dotnet/pull/183
The firmware update method did not provide all parameters for the updateProperty callback and so the firmware version was never correctly updated. 
This change adds in the correct calls to updateProperty and adds a DeviceMethodStatus update on the state of the firmware update. 
**Checklist:**
> Firmware update method calls updateProperty callback with all parameters

- Services.Test/DevicePropertiesRequestTest.cs
- Services/DeviceClient.cs
- Services/DeviceMethods.cs
- Services/DevicePropertiesRequest.cs
- Services/Devices.cs
- SimulationAgent/DeviceConnection/Connect.cs
- SimulationAgent/DeviceConnection/DeviceConnectionActor.cs
- SimulationAgent/DeviceState/DeviceStateActor.cs
Adds functionality for receiving notifications of Desired Property state changes from the IoT Hub. When the hub detects a state change it will send a notification via the `DeviceClient.SetDesiredPropertyUpdateCallbackAsync` registration. This change allows the simulation service to subscribe to the change notifications and update the internal simulation state to report the desired property to the hub when executed.
*Note:*
This registration is different from the way desired properties changes happened in RemoteMontioring V2 Preview, which was previously querying for changes on a set interval.
| File       | Description           |
| ------------- | ------------- |
| DeviceClient.cs |Add registration for desired properties callback |
| _[New]_ DevicePropertiesRequest.cs | Calls the azure …
> Register for Desired Property State Changes

- .travis.yml
- scripts/docker/Dockerfile
- scripts/docker/build
Since we removed the second process (simulation agent) running in the container, the simlink from `/app/webservice/data` to `/app/data` is not needed anymore.
Also, in some conditions (e.g. Docker 17 for Linux) the Docker build is failing to move files from `/app/webservice/data` to `/app/data` due to folder permissions.
Separately, we should update the comments in these files:
* https://github.com/Azure/pcs-cli/blob/master/solutions/remotemonitoring/single-vm/docker-compose.dotnet.yml
* https://github.com/Azure/pcs-cli/blob/master/solutions/remotemonitoring/single-vm/docker-compose.java.yml
* https://github.com/Azure/pcs-cli/blob/azure-iot-pcs-simulation/solutions/devicesimulation/single-vm/docker-compose.yml
* https://github.com/Azure/pcs-cli/blob/azure-iot-pcs-simulation/solutions/devic …
> Remove symlink to /app/data

- Services/Devices.cs
Currerntly the simulated devices contain the "simulated" prefix. Per design guidelines for [Remote Monitoring](https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/), the change removes the prefix as the information is given through the IsSimulated tag.
**Checklist:**
> Remove 'Simulated.' prefix for devices

- SimulationAgent/DeviceState/DeviceStateActor.cs
Adding telemetry information (a static copy of the 'Telemetry' node from the corresponding devicemodel JSON file) to the set of reported properties in a device's device twin. 
How verified: manually verified that the telemetry info is being written to the twins.
**Checklist:**
> Adding telemetry node to reported twin properties.

- Services/data/devicemodels/scripts/FirmwareUpdate-method.js
The FirmwareUpdate method reports the status of updates, which are written as reported properties in the twin (downloading, updating, updated, etc.). There were two properties being written to the twin: DeviceMethodStatus and FirmwareUpdateStatus. FirmwareUpdateStatus was always null. This change will result in DeviceMethodStatus not being reported to the twin. Only FirmwareUpdateStatus will be reported.
...
**Checklist:**
> Remove duplicate firmware-update related status keys in twin

- Services/Simulations.cs
- WebService/v1/Controllers/SimulationsController.cs
A POST with QP template=default should successfully create a simulation using default hub and all stock device models
...
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/264)
> Fix for creating Default Simulation

- .gitignore
- Services.Test/SimulationsTest.cs
- Services/Clustering/ClusterNodes.cs
- Services/Clustering/ClusteringConfig.cs
- Services/Devices.cs
- Services/Models/Simulation.cs
- Services/Simulations.cs
- Services/Storage/DocumentDb/DocumentDbWrapper.cs
- SimulationAgent.Test/SimulationRunnerTest.cs
- SimulationAgent/Agent.cs
- SimulationAgent/SimulationRunner.cs
- WebService/DependencyResolution.cs
- WebService/Runtime/Config.cs
- WebService/Runtime/ConfigFile.cs
- WebService/Startup.cs
- WebService/appsettings.ini
- device-simulation.sln
- device-simulation.sln.DotSettings
- scripts/development/postman_collection.json
The code ported from POC was missing some changes, e.g. Device IDs count starting from "1" instead of "0" and device IDs containing the simulation ID. As a result the simulation was creating more devices and using incorrect connection strings, leading to errors and incorrect metrics.
The PR includes also some minor housekeeping and a dev improvement to allow local settings. See the note at the start of appsettings.ini for more info. Quickly put: create a local file with the settings you want to override, store the file path in an env var (PCS_DEV_APPSETTINGS), and the service will use **also** those settings when running.
The PR includes also a Postman collection, so we can start sharing the REST calls and have a better dev experience.
**Checklist:**
---
This change is [<img …
> bugfix: use correct Device IDs

- Services.Test/DeviceClientTest.cs
- Services/DeviceClient.cs
- Services/IotHub/DeviceClientWrapper.cs
- SimulationAgent.Test/DeviceConnection/ConnectTest.cs
- SimulationAgent/DeviceConnection/Connect.cs
- SimulationAgent/DeviceConnection/DeviceConnectionActor.cs
When reconnecting a device, make sure the existing client is disposed, so that internal tasks in the SDK are stopped.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/289)
> When reconnecting a device, make sure the existing client is disposed

- Services/Devices.cs
- Services/IotHub/DeviceClientWrapper.cs
- Services/Runtime/ServicesConfig.cs
- WebService/Runtime/Config.cs
- WebService/appsettings.ini
Currently, the recipients of our telemetry data, ( for example: Hub team) have no way of determining if the message was received from Device Simulation. This could create a lot of problems for them during bursts of incoming traffic. 
And so, in this PR, we are tagging messages with a user agent string - "devicesimulation", indicating the source of the telemetry data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/294)
> Tagging telemetry messages with user agent 

- Services.Test/Statistics/SimulationStatisticsTest.cs
- Services/Simulations.cs
- Services/Statistics/SimulationStatistics.cs
- SimulationAgent.Test/SimulationManagerTest.cs
- SimulationAgent/SimulationManager.cs
1) Reset ActiveDevice count to 0 when simulation is stopped. Save stats to db.
2) Fix incorrect active device count calculation. Added check for key prefix while parsing dictionary.
3) Added unit tests.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/305)
> Reset Active devices

- SimulationAgent/Agent.cs
Today we noticed that telemetry wasn't being sent for some devices in some simulations. There may be a multi-layered problem here, but my investigation lead me to review the code where we define which telemetry actors the telemetry threads should work with. We use four telemetry threads to divide up the work of sending telemetry. There is a loop that specifies an index for each device-telemetry thread to use in order to calculate which actors to work on. The index was calculated and passed inline in a lambda, and it turns out that we were passing incorrect values (where we should have been passing 1, 2, 3, 4 to the threads, we were passing 2, 3, 4, 5). This meant that a large chunk of telemetry actors were never being called and their telemetry was not being sent. 
The fix is to calculate …
> Fixing a bug where telemetry wasn't sent for some devices.

- SimulationAgent/Agent.cs
If multiple simulations are active, stats for only one simulation was getting saved at specified interval. Fix: Moved the check for duration and saving lastSaveStats time outside the loop.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/307)
> Save stats for all simulations when multiple sims are running

- Services.Test/Statistics/SimulationStatisticsTest.cs
- Services/Statistics/SimulationStatistics.cs
Added a check for active device count calculation in GetSimulationStatisticsAsync to check of node is available in node collection (node collection contains only active nodes, expired nodes will be removed).
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/309)
> active device count for expired nodes

- SimulationAgent.Test/DeviceProperties/DevicePropertiesActorTest.cs
- SimulationAgent/DeviceProperties/DevicePropertiesActor.cs
We discovered that property updates were not being sent to the hub during a simulation. Investigating this, we found that we were incorrectly referencing a global ratelimiting object that was no longer available. I suspect that this was causing the property-update thread to crash. Referencing this global rate-limiting object was a hold-over from the pre-large-scale-simulation support codebase that I missed while porting the POC. 
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/311)
> Fixing a bug that was causing property updates to not be sent.

- Services.Test/DeviceClientTest.cs
- Services.Test/DevicePropertiesTest.cs
- Services/DeviceClient.cs
- Services/DeviceMethods.cs
- Services/DeviceProperties.cs
- Services/Devices.cs
- Services/IotHub/DeviceClientWrapper.cs
- Services/Runtime/ServicesConfig.cs
- SimulationAgent/Agent.cs
- SimulationAgent/DeviceTelemetry/DeviceTelemetryActor.cs
- SimulationAgent/DeviceTelemetry/SendTelemetry.cs
- WebService/Runtime/Config.cs
- WebService/Startup.cs
- WebService/appsettings.ini
New feature to:
* disable device twins and methods, so one can test scenarios where devices don't establish the extra connections for these hub's features. At the moment the flags are global, and with more work these could become simulation specific settings.
* recreate a device if the device is deleted while a simulation is running
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/331)
> Add options to disable device twins and methods

- Services/Devices.cs
- Services/IotHub/DeviceClientWrapper.cs
- Services/Runtime/ServicesConfig.cs
- WebService/Runtime/Config.cs
- WebService/appsettings.ini
Currently, the recipients of our telemetry data, (for example: IoT Hub team) have no way of determining if the message was received from Device Simulation or Remote Monitoring.
This PR tags messages with a user agent string indicating the source of the telemetry data.
Remote Monitoring is currently using DS-1.0.2, so this PR cherry-picks the commit from #294 to the DS-1.0.2 branch
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/337)
> Add UserAgent tagging to DS-1.0.x

- SimulationAgent/DeviceTelemetry/DeviceTelemetryActor.cs
- SimulationAgent/DeviceTelemetry/SendTelemetry.cs
- WebService/appsettings.ini
1. Advanced device models use long device names (guid.guid.count) which causes storage write exception due to char limit for large number of devices. Update partition size to 2000 to prevent storage error due to char limit.
2. Send telemetry sometimes throws null reference exception in some cases when device state is not set. This repros for custom device model when message size is huge. Added a check in telemetry actor to check for device state actor - if it is in active state then send telemetry. 
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/342)
> Custom model send telemetry updates

- Services.Test/Storage/CosmosDbSql/EngineTest.cs
- Services.Test/Storage/EnginesTest.cs
- Services/Storage/CosmosDbSql/Engine.cs
- WebService/Startup.cs
We recently observed some instances of the Simulation service stopping when it received unexpected exceptions from CosmostDB. I've added calls to the diagnostics service to gather data on this, as well as for when the process stops because one or both of the agent threads stop.
**Checklist:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/341)
> Diagnostics instrumentation for CosmostDB failures and application termination

- WebService/Auth/AuthMiddleware.cs
- WebService/Auth/ClientAuthConfig.cs
- WebService/Runtime/Config.cs
- WebService/WebService.csproj
- WebService/appsettings.ini
After roughly 2 months, the auth middleware had stale metadata for OpenIdConnect. This change adds a TTL for the OpenIdConnect object, after the TTL, the service will fetch a new instance.
https://github.com/Azure/remote-monitoring-services-dotnet/issues/233
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/azure/device-simulation-dotnet/356)
> Add Time-To-Live for Token Validation in Auth Middleware

- arm-deployment/devicesimulation-nohub/armtemplate/parameters.json
- arm-deployment/devicesimulation-nohub/armtemplate/template.json
- arm-deployment/devicesimulation-nohub/single-vm/docker-compose.yml
- arm-deployment/devicesimulation-nohub/single-vm/scripts/logs.sh
- arm-deployment/devicesimulation-nohub/single-vm/scripts/start.sh
- arm-deployment/devicesimulation-nohub/single-vm/scripts/stats.sh
- arm-deployment/devicesimulation-nohub/single-vm/scripts/status.sh
- arm-deployment/devicesimulation-nohub/single-vm/scripts/stop.sh
- arm-deployment/devicesimulation-nohub/single-vm/setup-wrapper.sh
- arm-deployment/devicesimulation-nohub/single-vm/setup.sh
- arm-deployment/devicesimulation-nohub/single-vm/setup/bashrc
- arm-deployment/devicesimulation-nohub/single-vm/setup/init
- arm-deployment/devicesimulation-nohub/single-vm/setup/nanorc
- arm-deployment/devicesimulation/armtemplate/parameters.json
- arm-deployment/devicesimulation/armtemplate/template.json
- arm-deployment/devicesimulation/single-vm/docker-compose.yml
- arm-deployment/devicesimulation/single-vm/scripts/logs.sh
- arm-deployment/devicesimulation/single-vm/scripts/start.sh
- arm-deployment/devicesimulation/single-vm/scripts/stats.sh
- arm-deployment/devicesimulation/single-vm/scripts/status.sh
- arm-deployment/devicesimulation/single-vm/scripts/stop.sh
- arm-deployment/devicesimulation/single-vm/setup-wrapper.sh
- arm-deployment/devicesimulation/single-vm/setup.sh
- arm-deployment/devicesimulation/single-vm/setup/bashrc
- arm-deployment/devicesimulation/single-vm/setup/init
- arm-deployment/devicesimulation/single-vm/setup/nanorc
- arm-deployment/readme.md
When you deploy Simulation from azureiotsolutions.com, a deployment process is kicked off which eventually references deployment-related files (for Simulation) from the pcs-cli repository. This change will break the dependency on the CLI and will enable the deployment process to pull the necessary files directly from this repository. 
Another nice thing about this change is that it will consolidate the VM setup scripts in to a single repository. 
There are a ton of files in this change. I'm not expecting a thorough review here. This is more of an FYI of the change.
The only actual file changes relate to references to the CLI repro in files such as in arm-deployment\devicesimulation*\armtemplate\parameters.json
**Checklist:**
> Adding ARM-deployment related files to Simulation.
